import {
  Award,
  IceCream,
  Star,
  Store,
  Trophy,
  Users,
  Heart,
  Map,
  Utensils,
  ThumbsUp,
  Clock,
  Calendar,
  Zap,
  Flame,
  Crown,
  Medal,
  Target,
  Flag,
  Compass,
  Bookmark,
  CheckCircle,
  Coffee,
  Smile,
  Droplet,
  Feather,
  Hexagon,
  Leaf,
  Snowflake,
  Sun,
  Sunset,
  Umbrella,
  Wind,
  Aperture,
  Palette,
  Camera,
  Music,
  Radio,
  Tv,
  Video,
  Film,
  Book,
  FileText,
  Folder,
  ImageIcon,
  Mail,
  MessageCircle,
  MessageSquare,
  Phone,
  Send,
  Share,
  Share2,
  Smartphone,
  Tablet,
  Tag,
  Trash,
  Trash2,
  Upload,
  Download,
  Cloud,
  Database,
  Server,
  Settings,
  Sliders,
  PenToolIcon as Tool,
  Wrench,
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Bell,
  BellOff,
  Eye,
  EyeOff,
  Filter,
  Key,
  Lock,
  Unlock,
  Search,
  ZoomIn,
  ZoomOut,
  Loader,
  RefreshCw,
  RotateCw,
  Save,
  Scissors,
  Clipboard,
  Printer,
  ShoppingBag,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Gift,
  Package,
  Percent,
  ShieldOff,
  ShieldAlert,
  ShieldCheck,
  Truck,
  Watch,
  Wifi,
  WifiOff,
  Bluetooth,
  Cast,
  Headphones,
  Mic,
  MicOff,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Airplay,
  Monitor,
  Paperclip,
  Link,
  Link2,
  Unlink,
  Maximize,
  Minimize,
  Plus,
  PlusCircle,
  PlusSquare,
  Minus,
  MinusCircle,
  MinusSquare,
  X,
  XCircle,
  XSquare,
  XOctagon,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ArrowDownCircle,
  ArrowLeftCircle,
  ArrowRightCircle,
  ArrowUpCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowUpRight,
  MoreHorizontal,
  MoreVertical,
  Grid,
  List,
  Menu,
  Square,
  Circle,
  Triangle,
  Octagon,
  Home,
  Hash,
  Inbox,
  Layers,
  Layout,
  LayoutDashboard,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Bold,
  Italic,
  Underline,
  Type,
  Edit,
  Edit2,
  Edit3,
  Copy,
  RotateCcw,
  ExternalLink,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserX,
  User,
  UserCheck,
  Briefcase,
  FolderMinus,
  FolderPlus,
  File,
  FileMinus,
  FilePlus,
  MapPin,
  PenToolIcon as Tool,
} from "lucide-react"

export const Icons = {
  award: Award,
  iceCream: IceCream,
  star: Star,
  store: Store,
  trophy: Trophy,
  users: Users,
  heart: Heart,
  map: Map,
  utensils: Utensils,
  thumbsUp: ThumbsUp,
  clock: Clock,
  calendar: Calendar,
  zap: Zap,
  flame: Flame,
  crown: Crown,
  medal: Medal,
  target: Target,
  flag: Flag,
  compass: Compass,
  bookmark: Bookmark,
  checkCircle: CheckCircle,
  coffee: Coffee,
  smile: Smile,
  droplet: Droplet,
  feather: Feather,
  hexagon: Hexagon,
  leaf: Leaf,
  snowflake: Snowflake,
  sun: Sun,
  sunset: Sunset,
  umbrella: Umbrella,
  wind: Wind,
  aperture: Aperture,
  palette: Palette,
  camera: Camera,
  music: Music,
  radio: Radio,
  tv: Tv,
  video: Video,
  film: Film,
  book: Book,
  fileText: FileText,
  folder: Folder,
  image: ImageIcon,
  mail: Mail,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  phone: Phone,
  send: Send,
  share: Share,
  share2: Share2,
  smartphone: Smartphone,
  tablet: Tablet,
  tag: Tag,
  trash: Trash,
  trash2: Trash2,
  upload: Upload,
  download: Download,
  cloud: Cloud,
  database: Database,
  server: Server,
  settings: Settings,
  sliders: Sliders,
  tool: Tool,
  wrench: Wrench,
  activity: Activity,
  alertCircle: AlertCircle,
  alertOctagon: AlertOctagon,
  alertTriangle: AlertTriangle,
  bell: Bell,
  bellOff: BellOff,
  eye: Eye,
  eyeOff: EyeOff,
  filter: Filter,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  search: Search,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  loader: Loader,
  refreshCw: RefreshCw,
  rotateCw: RotateCw,
  save: Save,
  scissors: Scissors,
  clipboard: Clipboard,
  printer: Printer,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  gift: Gift,
  package: Package,
  percent: Percent,
  shieldOff: ShieldOff,
  shieldAlert: ShieldAlert,
  shieldCheck: ShieldCheck,
  truck: Truck,
  watch: Watch,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  cast: Cast,
  headphones: Headphones,
  mic: Mic,
  micOff: MicOff,
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  volume: Volume,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  airplay: Airplay,
  monitor: Monitor,
  paperclip: Paperclip,
  link: Link,
  link2: Link2,
  unlink: Unlink,
  maximize: Maximize,
  minimize: Minimize,
  plus: Plus,
  plusCircle: PlusCircle,
  plusSquare: PlusSquare,
  minus: Minus,
  minusCircle: MinusCircle,
  minusSquare: MinusSquare,
  x: X,
  xCircle: XCircle,
  xSquare: XSquare,
  xOctagon: XOctagon,
  check: Check,
  checkSquare: CheckSquare,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  cornerDownLeft: CornerDownLeft,
  cornerDownRight: CornerDownRight,
  cornerLeftDown: CornerLeftDown,
  cornerLeftUp: CornerLeftUp,
  cornerRightDown: CornerRightDown,
  cornerRightUp: CornerRightUp,
  cornerUpLeft: CornerUpLeft,
  cornerUpRight: CornerUpRight,
  chevronsDown: ChevronsDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUp: ChevronsUp,
  arrowDownCircle: ArrowDownCircle,
  arrowLeftCircle: ArrowLeftCircle,
  arrowRightCircle: ArrowRightCircle,
  arrowUpCircle: ArrowUpCircle,
  arrowDownLeft: ArrowDownLeft,
  arrowDownRight: ArrowDownRight,
  arrowUpLeft: ArrowUpLeft,
  arrowUpRight: ArrowUpRight,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  grid: Grid,
  list: List,
  menu: Menu,
  square: Square,
  circle: Circle,
  triangle: Triangle,
  octagon: Octagon,
  hexagon: Hexagon,
  star: Star,
  home: Home,
  hash: Hash,
  inbox: Inbox,
  layers: Layers,
  layout: Layout,
  layoutDashboard: LayoutDashboard,
  alignCenter: AlignCenter,
  alignJustify: AlignJustify,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  type: Type,
  edit: Edit,
  edit2: Edit2,
  edit3: Edit3,
  copy: Copy,
  scissors: Scissors,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  externalLink: ExternalLink,
  cornerDownLeft: CornerDownLeft,
  cornerDownRight: CornerDownRight,
  cornerLeftDown: CornerLeftDown,
  cornerLeftUp: CornerLeftUp,
  cornerRightDown: CornerRightDown,
  cornerRightUp: CornerRightUp,
  cornerUpLeft: CornerUpLeft,
  cornerUpRight: CornerUpRight,
  logIn: LogIn,
  logOut: LogOut,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userX: UserX,
  user: User,
  userCheck: UserCheck,
  users: Users,
  briefcase: Briefcase,
  folder: Folder,
  folderMinus: FolderMinus,
  folderPlus: FolderPlus,
  file: File,
  fileMinus: FileMinus,
  filePlus: FilePlus,
  fileText: FileText,
  mapPin: MapPin,
}
