/**
 * Comprehensive manifest of critical files in the ConeDex Platform
 * This serves as the source of truth for file integrity checks
 */

export const CRITICAL_FILES = [
  // Core layout files
  "app/layout.tsx",
  "app/page.tsx",
  "pages/_app.tsx",
  "pages/index.tsx",

  // Layout components
  "components/layout/public-header.tsx",
  "components/layout/public-footer.tsx",
  "components/layout/dashboard-header.tsx",
  "components/layout/dashboard-sidebar.tsx",
  "components/layout/admin-header.tsx",
  "components/layout/admin-sidebar.tsx",

  // Core functionality
  "components/shop/simple-public-shops-map.tsx",
  "components/shop/public-shops-map.tsx",
  "lib/supabase/server.ts",
  "lib/supabase/client.ts",
  "lib/auth/demo-auth.ts",
  "app/api/auth/demo-login/route.ts",

  // Configuration
  "next.config.js",
  "tailwind.config.ts",
  "vercel.json",

  // Public routes
  "app/(public)/layout.tsx",
  "app/(public)/features/page.tsx",
  "app/(public)/pricing/page.tsx",
  "app/(public)/contact/page.tsx",
  "app/(public)/business/page.tsx",
  "app/(public)/shops/map/page.tsx",

  // Dashboard routes
  "app/(dashboard)/layout.tsx",
  "app/(dashboard)/dashboard/page.tsx",
  "app/(dashboard)/dashboard/shops/page.tsx",
  "app/(dashboard)/dashboard/flavors/page.tsx",
  "app/(dashboard)/dashboard/badges/page.tsx",
  "app/(dashboard)/dashboard/teams/page.tsx",
  "app/(dashboard)/dashboard/following/page.tsx",
  "app/(dashboard)/dashboard/notifications/page.tsx",

  // Admin routes
  "app/(dashboard)/dashboard/admin/page.tsx",
  "app/(dashboard)/dashboard/admin/users/page.tsx",
  "app/(dashboard)/dashboard/admin/shops/page.tsx",
  "app/(dashboard)/dashboard/admin/badges/page.tsx",
  "app/(dashboard)/dashboard/admin/settings/page.tsx",
  "app/(dashboard)/dashboard/admin/database/page.tsx",

  // Auth routes
  "app/(auth)/layout.tsx",
  "app/(auth)/login/page.tsx",
  "app/(auth)/signup/page.tsx",

  // Shop owner routes
  "app/(dashboard)/dashboard/shop/page.tsx",
  "app/(dashboard)/dashboard/shop/edit/page.tsx",
  "app/(dashboard)/dashboard/shop/flavors/page.tsx",
  "app/(dashboard)/dashboard/shop/customers/page.tsx",
  "app/(dashboard)/dashboard/shop/reviews/page.tsx",
  "app/(dashboard)/dashboard/shop/settings/page.tsx",
  "app/(dashboard)/dashboard/shop/menu/page.tsx",
  "app/(dashboard)/dashboard/shop/analytics/page.tsx",
  "app/(dashboard)/dashboard/shop/announcements/page.tsx",
  "app/(dashboard)/dashboard/shop/verify/page.tsx",
  "app/(dashboard)/dashboard/shop/subscription/page.tsx",

  // Core utilities
  "lib/utils/runtime-detection.ts",
  "lib/utils/runtime-utils.ts",
  "lib/utils/format-link.ts",
  "lib/utils/handle-api-error.ts",
  "lib/utils/offline-cache.ts",
  "lib/utils/offline-sync.ts",
  "lib/utils/api-client.ts",
  "lib/utils/form-validation.ts",
  "lib/utils/env-validator.ts",

  // Services
  "lib/services/location-service.ts",
  "lib/services/push-notification-service.ts",
  "lib/services/email-service.ts",
  "lib/services/stripe-service.ts",
  "lib/services/ai-service.ts",
  "lib/services/google-places-service.ts",
  "lib/services/subscription-service.ts",

  // Hooks
  "hooks/use-cached-data.ts",
  "hooks/use-feature-access.ts",
  "hooks/use-cached-feature-access.ts",
  "hooks/use-push-notifications.ts",
  "hooks/use-leaderboard.ts",
  "hooks/use-flavor-submission.ts",

  // Actions
  "app/actions/auth-actions.ts",
  "app/actions/leaderboard-actions.ts",
  "app/actions/newsletter-actions.ts",
  "app/actions/stripe-actions.ts",
  "app/actions/flavor-moderation.ts",
  "app/actions/shop-verification.ts",
  "app/actions/analytics.ts",
  "app/actions/generate-shop-report.ts",
  "app/actions/generate-flavor-catalog.ts",

  // API routes
  "app/api/maps/loader/route.ts",
  "app/api/maps/photo/route.ts",
  "app/api/push/subscribe/route.ts",
  "app/api/push/test/route.ts",
  "app/api/push/announcement/route.ts",
  "app/api/push/new-flavor/route.ts",
  "app/api/webhooks/stripe/route.ts",
  "app/api/admin/audit-logs/route.ts",
  "app/api/admin/shops/import/route.ts",
  "app/api/admin/users/import/route.ts",
  "app/api/admin/stripe/sync-products/route.ts",
  "app/api/admin/stripe/bulk-update-prices/route.ts",
  "app/api/admin/stripe/check-price-sync/route.ts",
  "app/api/admin/reports/scheduled/route.ts",
  "app/api/admin/reports/schedule/route.ts",
  "app/api/admin/scrape-shops/route.ts",
  "app/api/admin/import-shops/route.ts",
  "app/api/leaderboard/metrics/route.ts",
  "app/api/leaderboard/users/route.ts",
  "app/api/leaderboard/teams/route.ts",
  "app/api/testing/run-ui-tests/route.ts",
  "app/api/testing/visual-regression/route.ts",
  "app/api/testing/performance/route.ts",
  "app/api/charts/export/route.ts",

  // SQL files
  "db/seed-subscription-tier-features.sql",
  "db/leaderboard-tables.sql",
  "db/seed-leaderboard-metrics.sql",
  "db/seed-leaderboard-seasons.sql",
  "db/analytics-time-series-function.sql",
  "db/admin-audit-log.sql",
  "db/auto-moderation-schema.sql",
  "db/stripe-integration-schema.sql",
  "db/stripe-mapping-schema.sql",
  "db/add-stripe-mapping-table.sql",
  "db/add-price-amount-to-mapping.sql",
  "db/import-jobs-schema.sql",
  "db/shop-verification-schema.sql",
  "db/analytics-events-table.sql",
  "db/create-analytics-events-table.sql",
  "db/ai-analysis-columns.sql",
]

/**
 * Groups files by feature for more granular integrity checks
 */
export const FILE_GROUPS = {
  core: [
    "app/layout.tsx",
    "app/page.tsx",
    "pages/_app.tsx",
    "pages/index.tsx",
    "next.config.js",
    "tailwind.config.ts",
    "vercel.json",
  ],
  auth: [
    "lib/auth/demo-auth.ts",
    "app/api/auth/demo-login/route.ts",
    "app/(auth)/layout.tsx",
    "app/(auth)/login/page.tsx",
    "app/(auth)/signup/page.tsx",
    "lib/auth/session.ts",
    "lib/auth/pages-session.ts",
    "lib/auth/auth-compat.ts",
    "lib/auth/pages-auth.ts",
    "lib/auth/pages-demo-auth.ts",
    "contexts/auth-context.tsx",
    "contexts/pages-auth-context.tsx",
  ],
  maps: [
    "components/shop/simple-public-shops-map.tsx",
    "components/shop/public-shops-map.tsx",
    "app/(public)/shops/map/page.tsx",
    "app/(dashboard)/dashboard/shops/map/page.tsx",
    "app/api/maps/loader/route.ts",
    "app/api/maps/photo/route.ts",
    "lib/services/location-service.ts",
    "lib/services/google-places-service.ts",
    "components/maps/maps-api-loader.tsx",
  ],
  layout: [
    "components/layout/public-header.tsx",
    "components/layout/public-footer.tsx",
    "components/layout/dashboard-header.tsx",
    "components/layout/dashboard-sidebar.tsx",
    "components/layout/admin-header.tsx",
    "components/layout/admin-sidebar.tsx",
    "app/(public)/layout.tsx",
    "app/(dashboard)/layout.tsx",
    "app/(auth)/layout.tsx",
  ],
  supabase: [
    "lib/supabase/server.ts",
    "lib/supabase/client.ts",
    "lib/supabase/compat.ts",
    "lib/supabase/middleware-client.ts",
    "lib/supabase/pages-server.ts",
    "lib/supabase/pages-client.ts",
  ],
  dashboard: [
    "app/(dashboard)/dashboard/page.tsx",
    "app/(dashboard)/dashboard/shops/page.tsx",
    "app/(dashboard)/dashboard/flavors/page.tsx",
    "app/(dashboard)/dashboard/badges/page.tsx",
    "app/(dashboard)/dashboard/teams/page.tsx",
    "app/(dashboard)/dashboard/following/page.tsx",
    "app/(dashboard)/dashboard/notifications/page.tsx",
    "app/(dashboard)/dashboard/settings/page.tsx",
    "app/(dashboard)/dashboard/log-flavor/page.tsx",
    "app/(dashboard)/dashboard/my-conedex/page.tsx",
    "app/(dashboard)/dashboard/leaderboard/page.tsx",
  ],
  admin: [
    "app/(dashboard)/dashboard/admin/page.tsx",
    "app/(dashboard)/dashboard/admin/users/page.tsx",
    "app/(dashboard)/dashboard/admin/shops/page.tsx",
    "app/(dashboard)/dashboard/admin/badges/page.tsx",
    "app/(dashboard)/dashboard/admin/settings/page.tsx",
    "app/(dashboard)/dashboard/admin/database/page.tsx",
    "app/(dashboard)/dashboard/admin/analytics/page.tsx",
    "app/(dashboard)/dashboard/admin/moderation/page.tsx",
    "app/(dashboard)/dashboard/admin/verification/page.tsx",
    "app/(dashboard)/dashboard/admin/subscriptions/page.tsx",
    "app/(dashboard)/dashboard/admin/testing/page.tsx",
    "app/(dashboard)/dashboard/admin/newsletters/page.tsx",
    "app/(dashboard)/dashboard/admin/stripe-mapping/page.tsx",
  ],
  "shop-owner": [
    "app/(dashboard)/dashboard/shop/page.tsx",
    "app/(dashboard)/dashboard/shop/edit/page.tsx",
    "app/(dashboard)/dashboard/shop/flavors/page.tsx",
    "app/(dashboard)/dashboard/shop/customers/page.tsx",
    "app/(dashboard)/dashboard/shop/reviews/page.tsx",
    "app/(dashboard)/dashboard/shop/settings/page.tsx",
    "app/(dashboard)/dashboard/shop/menu/page.tsx",
    "app/(dashboard)/dashboard/shop/analytics/page.tsx",
    "app/(dashboard)/dashboard/shop/announcements/page.tsx",
    "app/(dashboard)/dashboard/shop/verify/page.tsx",
    "app/(dashboard)/dashboard/shop/subscription/page.tsx",
    "app/(dashboard)/dashboard/shop/marketing/page.tsx",
    "app/(dashboard)/dashboard/shop/profile/edit/page.tsx",
    "app/(dashboard)/dashboard/shop/claim/page.tsx",
  ],
  public: [
    "app/(public)/features/page.tsx",
    "app/(public)/pricing/page.tsx",
    "app/(public)/contact/page.tsx",
    "app/(public)/business/page.tsx",
    "app/(public)/about/page.tsx",
    "app/(public)/privacy/page.tsx",
    "app/(public)/terms/page.tsx",
    "app/(public)/sponsors/page.tsx",
    "app/(public)/help/page.tsx",
    "app/(public)/offline-features/page.tsx",
    "app/(public)/business/api/page.tsx",
    "app/(public)/business/claim/page.tsx",
  ],
  pwa: [
    "public/manifest.json",
    "public/offline.html",
    "components/ui/offline-indicator.tsx",
    "components/ui/install-prompt.tsx",
    "lib/hooks/use-cached-data.ts",
    "public/sw-register.js",
    "public/sw.js",
    "components/pwa/install-button.tsx",
    "lib/utils/offline-cache.ts",
    "lib/utils/offline-sync.ts",
    "lib/sw-registration.ts",
  ],
  notifications: [
    "components/notifications/notification-bell.tsx",
    "components/notifications/notification-item.tsx",
    "app/(dashboard)/dashboard/notifications/page.tsx",
    "components/notifications/notification-preferences.tsx",
    "app/(dashboard)/dashboard/settings/notifications/page.tsx",
    "app/api/push/subscribe/route.ts",
    "app/api/push/test/route.ts",
    "app/api/push/announcement/route.ts",
    "app/api/push/new-flavor/route.ts",
    "lib/services/push-notification-service.ts",
    "hooks/use-push-notifications.ts",
  ],
  subscription: [
    "hooks/use-feature-access.ts",
    "app/(dashboard)/dashboard/shop/subscription/page.tsx",
    "lib/actions/check-feature-access.ts",
    "components/subscription/server-feature-gate.tsx",
    "components/subscription/subscription-status.tsx",
    "components/subscription/feature-gate.tsx",
    "app/(dashboard)/dashboard/admin/subscriptions/page.tsx",
    "components/subscription/subscription-banner.tsx",
    "db/seed-subscription-tier-features.sql",
    "components/subscription/feature-comparison.tsx",
    "components/admin/edit-subscription-tier-modal.tsx",
    "components/admin/add-subscription-tier-modal.tsx",
    "lib/services/subscription-service.ts",
  ],
  stripe: [
    "lib/services/stripe-service.ts",
    "app/api/webhooks/stripe/route.ts",
    "db/stripe-integration-schema.sql",
    "components/subscription/stripe-checkout-button.tsx",
    "scripts/setup-stripe-products.ts",
    "db/stripe-mapping-schema.sql",
    "app/api/admin/stripe/sync-products/route.ts",
    "db/add-stripe-mapping-table.sql",
    "app/(dashboard)/dashboard/admin/stripe-mapping/page.tsx",
    "lib/utils/get-stripe-price.ts",
    "db/add-price-amount-to-mapping.sql",
    "app/actions/stripe-actions.ts",
    "components/admin/stripe-product-mapping-form.tsx",
    "components/admin/stripe-price-sync-status.tsx",
    "components/admin/stripe-bulk-update.tsx",
    "app/api/admin/stripe/bulk-update-prices/route.ts",
    "components/admin/stripe-product-mapping.tsx",
    "app/api/admin/stripe/check-price-sync/route.ts",
  ],
  leaderboard: [
    "app/(dashboard)/dashboard/leaderboard/page.tsx",
    "components/leaderboard/team-ranking.tsx",
    "app/(dashboard)/dashboard/teams/[id]/page.tsx",
    "components/leaderboard/leaderboard-tabs.tsx",
    "components/leaderboard/metric-selector.tsx",
    "components/leaderboard/season-selector.tsx",
    "components/leaderboard/metric-icon.tsx",
    "components/leaderboard/user-rank-badge.tsx",
    "components/leaderboard/team-leaderboard.tsx",
    "db/leaderboard-tables.sql",
    "db/seed-leaderboard-metrics.sql",
    "db/seed-leaderboard-seasons.sql",
    "components/leaderboard/user-ranking.tsx",
    "hooks/use-leaderboard.ts",
    "app/api/leaderboard/metrics/route.ts",
    "app/api/leaderboard/users/route.ts",
    "app/api/leaderboard/teams/route.ts",
    "lib/utils/leaderboard-utils.ts",
    "app/(dashboard)/dashboard/teams/page.tsx",
    "components/dashboard/leaderboard-widget.tsx",
    "app/actions/leaderboard-actions.ts",
    "components/leaderboard/user-leaderboard.tsx",
  ],
  analytics: [
    "app/(dashboard)/dashboard/admin/analytics/page.tsx",
    "components/admin/analytics/installation-metrics.tsx",
    "components/admin/analytics/engagement-metrics.tsx",
    "components/admin/analytics/platform-breakdown.tsx",
    "components/admin/analytics/feature-usage.tsx",
    "components/admin/analytics/retention-chart.tsx",
    "components/admin/analytics/user-activity-heatmap.tsx",
    "components/admin/analytics/export-analytics.tsx",
    "components/admin/analytics/custom-reports.tsx",
    "components/admin/analytics/conversion-funnels.tsx",
    "components/admin/analytics/user-segments.tsx",
    "components/admin/analytics/real-time-dashboard.tsx",
    "db/analytics-time-series-function.sql",
    "components/admin/analytics/chart-export-tool.tsx",
    "app/(dashboard)/dashboard/admin/analytics/exports/page.tsx",
    "lib/utils/chart-exporter.ts",
    "app/api/charts/export/route.ts",
    "components/admin/analytics/app-usage-overview.tsx",
    "db/analytics-events-table.sql",
    "app/actions/analytics.ts",
    "components/analytics/analytics-tracker.tsx",
    "components/analytics/analytics-toggle.tsx",
    "db/create-analytics-events-table.sql",
  ],
  testing: [
    "lib/testing/integration-tests.ts",
    "components/admin/testing/integration-test-runner.tsx",
    "app/(dashboard)/dashboard/admin/testing/page.tsx",
    "lib/testing/puppeteer-tests.ts",
    "components/admin/testing/puppeteer-test-runner.tsx",
    "app/api/testing/run-ui-tests/route.ts",
    "lib/testing/visual-regression.ts",
    "app/api/testing/visual-regression/route.ts",
    "components/admin/testing/visual-regression-tester.tsx",
    "lib/testing/performance-monitor.ts",
    "app/api/testing/performance/route.ts",
    "components/admin/testing/performance-test-runner.tsx",
    "lib/testing/accessibility-testing.ts",
  ],
  email: [
    "lib/email-templates/base-template.ts",
    "lib/email-templates/welcome-template.ts",
    "lib/email-templates/password-reset-template.ts",
    "lib/email-templates/verification-template.ts",
    "lib/email-templates/notification-template.ts",
    "lib/email-templates/shop-follow-template.ts",
    "lib/email-templates/new-flavor-template.ts",
    "lib/email-templates/newsletter-template.ts",
    "lib/email-templates/shop-claim-approved-template.ts",
    "lib/email-templates/shop-claim-rejected-template.ts",
    "lib/email-templates/index.ts",
    "lib/services/email-service.ts",
    "components/admin/newsletters/newsletter-form.tsx",
    "components/admin/newsletters/newsletter-dashboard.tsx",
    "components/admin/editor.tsx",
    "app/(dashboard)/dashboard/admin/newsletters/page.tsx",
    "app/(dashboard)/dashboard/admin/newsletters/[id]/page.tsx",
    "app/(dashboard)/dashboard/admin/newsletters/[id]/edit/page.tsx",
    "components/admin/newsletters/newsletter-edit-form.tsx",
    "components/admin/newsletters/newsletter-item.tsx",
    "components/admin/newsletters/newsletter-skeleton.tsx",
    "components/admin/newsletters/newsletter-preview.tsx",
    "components/admin/newsletters/send-newsletter-form.tsx",
    "components/admin/newsletters/newsletter-list.tsx",
  ],
  import: [
    "components/admin/batch-import/import-progress.tsx",
    "app/api/admin/shops/import/[importId]/progress/route.ts",
    "app/api/admin/users/import/[importId]/progress/route.ts",
    "db/import-jobs-schema.sql",
    "app/(dashboard)/dashboard/admin/shops/import/page.tsx",
    "app/api/admin/shops/import/route.ts",
    "app/actions/admin/import-users.ts",
    "app/api/admin/users/template/route.ts",
    "components/admin/users/import-users-modal.tsx",
    "components/admin/users/import-users-button.tsx",
    "app/(dashboard)/dashboard/admin/users/page.tsx",
    "components/admin/users/import-users.tsx",
    "components/admin/users/import-documentation.tsx",
    "components/admin/users/import-results.tsx",
    "app/api/admin/users/import/actions.ts",
    "lib/utils/web-scraper.ts",
    "components/admin/shop-scraper.tsx",
    "app/api/admin/scrape-shops/route.ts",
    "app/api/admin/import-shops/route.ts",
  ],
  verification: [
    "app/(dashboard)/dashboard/shop/verify/page.tsx",
    "app/(dashboard)/dashboard/admin/verification/page.tsx",
    "db/shop-verification-schema.sql",
    "components/shop/verification/document-upload.tsx",
    "components/shop/verification/verification-form.tsx",
    "components/shop/verification/verification-badge.tsx",
    "app/actions/shop-verification.ts",
  ],
  moderation: [
    "app/(dashboard)/dashboard/admin/moderation/page.tsx",
    "db/auto-moderation-schema.sql",
    "lib/services/ai-service.ts",
    "app/actions/flavor-moderation.ts",
    "components/admin/ai-analysis-results.tsx",
    "db/ai-analysis-columns.sql",
  ],
  audit: ["db/admin-audit-log.sql", "components/admin/audit-log-viewer.tsx", "app/api/admin/audit-logs/route.ts"],
  "batch-processing": [
    "components/admin/batch-processor.tsx",
    "app/api/admin/batch-process/route.ts",
    "lib/utils/report-scheduler.ts",
    "components/admin/report-scheduler.tsx",
    "app/api/admin/reports/scheduled/route.ts",
    "app/api/admin/reports/schedule/route.ts",
    "app/api/admin/reports/[id]/toggle/route.ts",
    "lib/utils/batch-processor.ts",
  ],
  runtime: [
    "lib/utils/runtime-detection.ts",
    "lib/utils/runtime-utils.ts",
    "lib/webpack/runtime-detection-plugin.js",
    "lib/webpack/runtime-detection-plugin.mjs",
    "scripts/set-runtime-env.js",
    "scripts/verify-build.js",
  ],
}

/**
 * Maps Pages Router files to their App Router equivalents
 * This is used for tracking migration progress
 */
export const MIGRATION_MAP = {
  // Core pages
  "pages/index.tsx": "app/page.tsx",
  "pages/404.tsx": "app/not-found.tsx",
  "pages/500.tsx": "app/error.tsx",
  "pages/_app.tsx": "app/layout.tsx",
  "pages/_document.tsx": "app/layout.tsx",

  // Auth pages
  "pages/login.tsx": "app/(auth)/login/page.tsx",
  "pages/signup.tsx": "app/(auth)/signup/page.tsx",

  // Dashboard pages
  "pages/dashboard/index.tsx": "app/(dashboard)/dashboard/page.tsx",
  "pages/dashboard/shops.tsx": "app/(dashboard)/dashboard/shops/page.tsx",
  "pages/dashboard/conedex.tsx": "app/(dashboard)/dashboard/conedex/page.tsx",
  "pages/dashboard/badges.tsx": "app/(dashboard)/dashboard/badges/page.tsx",
  "pages/dashboard/teams.tsx": "app/(dashboard)/dashboard/teams/page.tsx",
  "pages/dashboard/following.tsx": "app/(dashboard)/dashboard/following/page.tsx",
  "pages/dashboard/notifications.tsx": "app/(dashboard)/dashboard/notifications/page.tsx",
  "pages/dashboard/profile.tsx": "app/(dashboard)/dashboard/profile/page.tsx",
  "pages/dashboard/settings.tsx": "app/(dashboard)/dashboard/settings/page.tsx",
  "pages/dashboard/flavors.tsx": "app/(dashboard)/dashboard/flavors/page.tsx",
  "pages/dashboard/log-flavor.tsx": "app/(dashboard)/dashboard/log-flavor/page.tsx",

  // Shop owner pages
  "pages/dashboard/shop/index.tsx": "app/(dashboard)/dashboard/shop/page.tsx",

  // Admin pages
  "pages/dashboard/admin/index.tsx": "app/(dashboard)/dashboard/admin/page.tsx",

  // Add more pages as needed
}
